services:
  app:
    build:
      context: ./
      dockerfile: dockerfiles/app/Dockerfile
    ports:
      - "2048:3000"
    volumes:
      - .:/src
    restart: always
    depends_on:
      - database

  database:
    build:
      context: ./
      dockerfile: dockerfiles/database/Dockerfile
    ports:
      - "5069:3306"
    environment:
      MYSQL_DATABASE: games_db
      MYSQL_USER: dandelionWriter
      MYSQL_PASSWORD: 0908072244!
      MYSQL_ROOT_PASSWORD: 0908072244X!
    volumes:
      - ./mysql-data:/var/lib/mysql